---
title: "Module 4 Challenge 5 Data Coercion"
author: "Zach C"
date: "September 24, 2017"
output: html_document
---

#**Store the following numbers as a 5 x 3 matrix: 3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2. Be sure to fill the matrix ROWWISE.**

#**Then, do the following:**

#**Coerce the matrix to a data frame.**

#**As a data frame, coerce the second column to be logical-valued**

#**As a data frame, coerce the third column to be factor-valued**

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

m<-matrix(data=c(3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2),nrow=5,ncol=3,byrow=TRUE)
> m
     [,1] [,2] [,3]
[1,]    3    0    1
[2,]   23    1    2
[3,]   33    1    1
[4,]   42    0    1
[5,]   41    0    2
> 
> df <- data.frame(m)
> df
  X1 X2 X3
1  3  0  1
2 23  1  2
3 33  1  1
4 42  0  1
5 41  0  2
> 
> ?as.logical()
> as.logical(df[,c(2)])
[1] FALSE  TRUE  TRUE FALSE FALSE
>
> as.factor(df[,c(3)])
[1] 1 2 1 1 2
Levels: 1 2

> str(df)
'data.frame':	5 obs. of  3 variables:
 $ X1: num  3 23 33 42 41
 $ X2: num  0 1 1 0 0
 $ X3: num  1 2 1 1 2
```
#**Notes on Data Frames**

#>Example of DF production
#df <- data.frame(firstName = c("Nitin", "Silvy", "Ingrid", "Claire"), program = c("iSchool", "Anthro", "Anthro", "EEB"), sex = c("M", "F", "F", "F"), yearInProgram = c(1, 2, 2, 3))

##        firstName      program        sex       yearInProgram
## 1      Nitin          iSchool        M             1
## 2      Silvy          Anthro         F             2
## 3      Ingrid         Anthro         F             2
## 4      Claire         EEB            F             3

#> df[, c(1, 3, 4, 11, 12)] - use to print only select columns of the data frame

#>make sure entire file is in quotations for the df to properly run 

#>You can add rows (additional cases) or columns (additional variables) to a data frame using rbind() and cbind().

#>cbind() results in school being added as a factor while using the $ operator results in school being added as a character vector. You can see this by using the str() command.

#>You can subset a data frame by the function new_df <- df[df$school == "BU", ], for example, where you only want students under variable School=BU selected

#>You can also choose to only return particular columns when we subset via the funtion new_df <- df[df$school == "BU", c("name.last", "name.first", "school")]

#>R tends to import character string data as factors, assigning to each unique string to an integer numeric code and assigning the string as a “label” for that code. You can convert factor to character data (and vice versa) using the as.character() or as.factor() commands
